# Generated by Django 4.1.1 on 2022-12-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_oldprice', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='productimage')),
            ],
        ),
    ]
