# Generated by Django 4.1.1 on 2022-12-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='GymProducts',
        ),
    ]
