# Generated by Django 4.1.1 on 2022-12-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_products_gymproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymproducts',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gymproducts',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='gymproducts',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gymproducts',
            old_name='product_oldprice',
            new_name='oldprice',
        ),
        migrations.RenameField(
            model_name='gymproducts',
            old_name='product_price',
            new_name='price',
        ),
    ]
