# Generated by Django 4.1.1 on 2022-12-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
