# Generated by Django 4.1.1 on 2022-12-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
