# Generated by Django 4.1.1 on 2022-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=30)),
                ('guest_email', models.CharField(max_length=30)),
                ('guest_phone', models.CharField(max_length=30)),
                ('guest_subject', models.CharField(max_length=30)),
                ('guest_message', models.TextField(max_length=1000)),
            ],
        ),
    ]
