# Generated by Django 4.1.1 on 2022-12-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.CharField(max_length=30)),
                ('package_duration', models.CharField(max_length=50)),
                ('package_timing', models.CharField(max_length=90)),
                ('package_days', models.CharField(max_length=200)),
                ('package_image', models.ImageField(upload_to='packageimage')),
            ],
        ),
    ]
