# Generated by Django 4.1.1 on 2022-12-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='GymPackages',
        ),
    ]
